### ISSUE TITLE
Opcode traits naming

### ISSUE THREAD

**Issue by vovapolu** [expload/pravda#113]
`asm` module has `Op` trait for inner representation of opcodes. `dotnet` module has similar `OpCode` trait for CIL opcodes. It produces ambigous code during translation, we take `Op`s and create `OpCode`s. So I suggest to choose more unabigous naming for these two entities: `AsmOp` and `CilOp` or just `Op` with diffrenet prefix pacakges (`asm.Op`, `dotnet.Op`).

**Comment by sherzodv** [comment]
Idea with package prefixes is nice.
