### ISSUE TITLE
C# classes translation

### ISSUE THREAD

**Issue by vovapolu** [expload/pravda#153]
We plan to translate C# classes to `struct` [data format](https://github.com/expload/pravda/blob/master/doc/ref/vm/data.md) in our VM. 

Here are some important points of C# classes translation:
1. Each such class must have `[Translated]` attribute (therefore only classes with `[Translated]` or `[Program]` attributes are allowed in sources files to be translated, `[Program]` attribute marks classes that will be translated to programs, `[Translated]` attribute marks inner data structures )
2. Interfaces are not translated, they serve only as a compile-time entities, therefore they don't have to be marked with any attribute. 
3. We translate **all** (`private`, `protected`, `internal` and `public`) fields to `utf8("<field_name>") -> <field_value>` pairs in `struct`. 
4. We translate **all** methods to `utf8("<method_name>_<args_types>")` -> `utf8("<inner_function_name>")`. The `<args_types>` prefix is needed to support overloading and `<inner_function_name>` means name of function that will be called for the `<method_name>` method. Overridden methods will point to different `<inner_function_name>`. 
5. We translate `static` fields to storage items with `utf8("<class_name>_<field_name>")` keys. 
6. We translate `static` methods to regular functions with `<class_name>_<method_name>_<args_types>` names. 
7. Constructors will be translated to regular functions with `<class_name>_init_<args_types>` names. 

### Example:
Suppose we have the following class definition in C#:
```c#
interface Vehicle
{
  void ComeIn(String someone);
}

[Translated]
class Bicycle : Vehicle 
{
  public String Owner = "no one"; 

  void ComeIn(String someone) {
    Owner = someone; 
  }
} 

[Translated]
class Car : Vehicle  
{
  static private bool isBearBurnedDown = false;
  static public bool IsBearBurnedDown() 
  {
    return Car.isBearBurnedDown; 
  }

  public int NumberOfTires; 

  public Car(int tires)
  {
    NumberOfTires = tires. 
  }

  void ComeIn(String someone)
  {
    if (someone == "bear") {
      Car.isBearBurnedDown = true; 
    }
  }
}
```

- `interface Vehicle` won't be translated to anything
- `Bicycle()` constructor will be translated to `Bicycle_init` function that creates `struct(utf8("Owner") -> utf8("no one"), utf8("ComeIn_String") -> utf8("function1")`
- `Bicycle.ComeIn` will be translated to some function (let's call it `function1`) that changes `utf8("Owner")` field in the given `struct`. 
- `Car(int)` constructor will be translated to `Car_init_int` function that creates `struct(utf8("NumberOfTires") -> int32(<given_int>), utf8("ComeIn_String") -> utf8("function2"))`
- `isBearBurnedDown` static field will be translated to `utf8("Car_isBearBurnedDown") -> bool` storage item
- `IsBearBurnedDown` static method will be translated to `Car_IsBearBurnedDown` function that reads `utf8("Car_isBearBurnedDown")` storage key. 
- `Car.ComeIn` will be translated to some function (let's call it `function2`) that changes `utf8("Car_isBearBurnedDown") -> bool` storage item according to the given `String` from the stack.

**Comment by fomkin** [comment]
Can we replace all this string concatenations with uint16 identifiers? This is important because final size of binary should be as small as possible.

**Comment by fomkin** [comment]
Why we need `[Translated]` attribute? What will happen with classes which is not annotated with `[Translated]` or `[Program]`? What will happen with lambdas or another compile-time magic. Will be awesome if you will keep in mind support of F#. I sure it makes a lot of hidden service classes.

**Comment by fomkin** [comment]
I'm not sure that static fields should be stored by default. It looks like dark magic. Also what about constants? They will be stored too? Therefore I propose add special attribute for this feature.
