### ISSUE TITLE
Some way for game developers to pay XCoins for user

### ISSUE THREAD

**Issue by vovapolu** [expload/pravda#215]
Game developers will mostly accept GameTokens (not XCoins) from users of their games, but program execution in Pravda costs some fee that is charged in XCoins. We need some way to charge that fee from gave developer, not from user, because user shoudn't have XCoins on their accounts in general.

**Comment by vovapolu** [comment]
I suggest to add the new opcode `PAYFOR` indicating that the **program's owner** pays for used watts, not the **executor**. `PAYFOR` takes `limit: bigint` from the stack where `limit` is the maximum amount of XCoins program's owner can pay for executor. If amount of used watts is more than `limit` than executor pays the difference from his account. If amount of used watts if less than `limit` than program's owner pays only this spent amount, not `limit`. `PAYFOR` opcodes can be organized as a chain, executor should do some actions to accrue the next portion of program's owner money. 

This scheme opens the possibility obvious attack -- attacker is able to call program's methods endlessly resulting in spending all of program's owner money. The solution here is to oblige executor to pay GameTokens for called methods. For example, executor has to pay a little amount of GameTokens before every method for watts that are needed for determining which method executor is calling and bigger amount of GameTokens in the beginning of each method for watts that are needed to process the executor request. 

Executor isn't able to exchange XCoins for GameTokens, he is able only to spent these XCoins on watts necessary for program execution. 

The main problem I seeing now is how to determine the `limit` that on one hand is big enough to allow execution of program's method and on the other hand is safe for program's owner (if executor does some unexpected actions he can possible spend a lot of owner's money).

**Comment by Chicker** [comment]
>  If amount of used watts is more than limit than executor pays the difference from his account.

What should we do if the user has no enough XCoins (for instance, the fresh user account has zero XCoins)?

> **The solution here is to oblige executor to pay GameTokens for called methods**. For example, executor has to pay a little amount of GameTokens before every method for watts that are needed for determining which method executor is calling and bigger amount of GameTokens in the beginning of each method for watts that are needed to process the executor request.

Here there is a user's problem. For example, the user wants to buy some in-app game item, for instance, its cost is 500 GameTokens. At the moment, the user has no enough Game Tokens on his balance, thus it should buy them for a real money. After some time, the user has bought 500 GameTokens, so its balance is equal to 500 GameTokens. "Ok, the user is thinking, I'm having enough money to buy that dream sword". But when the user tries to buy the sword, the Platform says him "Sorry, you have no enough GameTokens to pay our tax". I think the user will be angry)

**Comment by vovapolu** [comment]
>if the user has no enough XCoins

The transaction will be aborted with `OutOfWatts` error as usual. 
> equal to 500 GameTokens

The program's owner sets tax amount by his own, he could set tax as 10 GameTokens, the price of item as 490 GameTokens and list the price of item as 500 GameTokens. User must always confirm how much he's paying in the Expload app, so user wouldn't even think about the tax if everything is working properly.

**Comment by Chicker** [comment]
> The transaction will be aborted with OutOfWatts error as usual.

And what the next? What should the user do next in order to complete his purchasing?

>The program's owner sets tax amount by his own, he could set tax as 10 GameTokens,

Ok, in that case, (1) the program's owner should calculate that tax **in advance** and include it in the resulting price of the item. And (2) the program's owner (or Platform) should guarantee that this tax is enough to complete the user's purchasing, in the other words the user should buy only 500 GameTokens and this amount is enough. Is possible to satisfy those two requirements? Can we replace ```limit``` to ```fix``` amount of XCoins? Can we use ```dryRun``` method for this?

**Comment by vovapolu** [comment]
I understood there's another problem with this scheme of exchanging XCoins watts for GameTokens. The exchange rate of XCoins can change very rapidly (as we can see in the current crypto-tranding), but GameTokens exchange rate is fixed. There can be situation where watts spent by transaction costs a way more than GameTokens for the item and tax. 

I can suggest to make GameToken tax dependent on some value in the storage, thereby program's onwer could change this value and regulate the desired tax.

**Comment by vovapolu** [comment]
@Chicker 

>What should the user do next in order to complete his purchasing?

Nothing, it's not his problem. At this case storage won't be changed, so user won't transfer any GameTokens. Only program's owner XCoins will be charged for transaction watts

>Can we use dryRun method for this?

Yes, we definitely run `dryRun` first. We determine how much GameTokens the user will pay and whether the "advance payment" from program's owner is enough to execute the transaction. The user **see** how much GameTokens he's transferring when confirming the transaction.

**Comment by Chicker** [comment]
>I understood there's another problem with this scheme of exchanging XCoins watts for GameTokens. The exchange rate of XCoins can change very rapidly (as we can see in the current crypto-tranding), but GameTokens exchange rate is fixed. There can be situation where watts spent by transaction costs a way more than GameTokens for the item and tax.

Yes, this problem was raised due to making the decision to exchange GameTokens on XCoins to pay the tax for transaction execution. As result, the game developer should change the tax and consequently the resulting price in GameTokens for each item in the marketplace when the XCoin exchange rate will significantly be changed. So we will get the indirect but stable relation between GameTokens and XCoins. The using the GameTokens in the machinery of the transaction execution will be reflected in the resulting price of the item on the marketplace. Should we agree with such a compromise?

>Yes, we definitely run dryRun first. We determine how much GameTokens the user will pay and whether the "advance payment" from program's owner is enough to execute the transaction. The user see how much GameTokens he's transferring when confirming the transaction.

I think the end user should not be worried about "how much GameTokens he is transferring...", it should know only about the end price in GameTokens of the item in the marketplace (say, the item price is 500 GameTokens). IMHO, the real tax should be hidden from the end user.

**Comment by vovapolu** [comment]
>Should we agree with such a compromise? 

It's not a big compromise. The watts price is regulated by validators, it shouldn't affect significantly the price of transaction in the long run. The only real problem here is very rapid jumps of exchange rate. 

> the real tax should be hidden from the end user

We give a freedom for developer to hide it or not. We are the platform, we should only properly support the necessary mechanism.  We guarantee that user see exactly how much money he's transfering for each transaction.

**Comment by fomkin** [comment]
Execution of program will be not started because `OutOfWatt` exception? Why? Because executor has no XCoins to prepay watts to run `PAYFOR`.

**Comment by fomkin** [comment]
After discussion with @vovapolu there is only one possible method I see. Lets's add two new optional fields: `wattPayer: Address` and `wattPayerSignature: ByteString` to Transaction. When processing transactions if `wattPayer` and `wattPayerSignature` is non-empty use `wattPayer` account to buy watts.

In case of GameTokens we will create a service which will check that transaction is valid (this will be very complex validation, we need dedicated discussion). The service will give it's signature. So when user want to send transaction and he has only GameTokens he need to get approve of transaction on the service.

**Comment by vovapolu** [comment]
@fomkin Ok, sounds fine. This scheme is quite similar to off-chain solutions like [0x protocol](https://0xproject.com/pdfs/0x_white_paper.pdf). The service will be off-chain, as I understand, so it will act as some off-chain channel to pass (implicitly through our system) user orders to game developers. The game developers here will act as "takers" and perform the given transaction (although it would seem like **user** perform actions in the blockchain). Probably we can think of more general solution for such behavior, but on the other hand we do it only to support GameTokens, which is the very particular thing for our solution.
