### ISSUE TITLE
The returning type of the "MyBalance" method of the "GameToken" program is changed after calling the "Spend" method

### ISSUE THREAD

**Issue by Chicker** [expload/pravda#249]
The first call of the method `MyBalance` returns the value of the right `UInt32` type. For instance,

```
{
  "spentWatts" : 437,
  "refundWatts" : 0,
  "totalWatts" : 437,
  "stack" : [ "uint32(1100)" ],
  "heap" : [ ]
}
```

 But after calling the method `Spend`, the all consequent calls of the method `MyBalance` return the value of unexpected `Int32` type:

```
{
  "spentWatts" : 437,
  "refundWatts" : 0,
  "totalWatts" : 437,
  "stack" : [ "int32(1300)" ],
  "heap" : [ ]
}
```

**Comment by fomkin** [comment]
Looks like this issue should be in GT repository.

**Comment by vovapolu** [comment]
@Chicker is it still relevant? We removed `uint*` primitives.

**Comment by Chicker** [comment]
> @Chicker is it still relevant? We removed `uint*` primitives.

I think such bug should not be reproduced after ridding of `uint` primitives.
