### ISSUE TITLE
Rewrite the "addWattPayerSignature" function

### ISSUE THREAD

**Issue by Chicker** [expload/pravda#250]
https://github.com/expload/pravda/blob/7698eb64e3b60fe2b573aab045c398648950d0b8/node/src/main/scala/pravda/node/data/cryptography.scala#L92-L96

This function doesn't make sense without the setting of `wattPayer` field since these both fields are mandatory if we want to charge a pay from the `wattPayer`.

I suggest to replace that function to the following function:

```
def addWattPayer(wattPayer: Address, privateKey: PrivateKey, tx: SignedTransaction): SignedTransaction = {
    val message = transcode(tx.forSignature).to[Bson]
    val signature = ed25519.sign(privateKey.toByteArray, message)
    tx.copy(wattPayer = Some(wattPayer), wattPayerSignature = Some(ByteString.copyFrom(signature)))
  }
```

**Comment by fomkin** [comment]
Well. In current implementation author of transaction have to know watt payer. So `tx` should be passed with non-empty `wattPayer` field.

**Comment by fomkin** [comment]
Actually I think current implementation of delegated watt payement is not convenient.
