### ISSUE TITLE
Convenient JSON presentation for Data

### ISSUE THREAD

**Issue by fomkin** [expload/pravda#266]
Currently we have convenient text `Data` presentation. It's human readable, and we have parsers written in Scala. But parsing this presentation in other languages is difficult. Idea is to make easy-to-parse JSON presentation for Data.

### Primitives

All primitives (except boolean and null) encodes as JSON strings with prefix. It's easy to parse. Most of popular languages have `indexOf` and `substring` functions.  Type always before first colon, value after.

```json
"int8:-100"
"int16:-100" 
"int32:-100"
"uint8:100"
"uint16:100"
"uint32:1000"
"bitint:9999999999999"
"number:2.0"
"ref:1"
"true" | "false"
"utf8:i am cow"
"bytes:01fca4e91"
"null"
```

### Arrays

Arrays corresponds to JSON arrays. First item contains type of primitive.

```json
["int32", "100", "200", "300"]
```

### Structs

Structs corresponds to JSON objects.

```json
{
  "utf8:user": "ref:9153",
  "int32:1432": "bytes:41f8cff6"
}
```

**Comment by vovapolu** [comment]
We should carefully think about `number`. Sometimes it's impossible to print floating point number as string without losing precision. May we lose precision or not when sending this message to the user? We could print `number` as hex or base64 string, but this would make parsing harder.

**Comment by fomkin** [comment]
@vovapolu What do you mean? We already print floating point numbers as strings in our text presentation.

**Comment by vovapolu** [comment]
I'd also change `.` to `:`, it'd look a little bit similar to Scala or Haskell type definitions.

**Comment by vovapolu** [comment]
@fomkin Yeah, sorry, I mean print as human-readable string, e.g. in finite decimal form.

**Comment by fomkin** [comment]
> I'd also change . to :, it'd look a little bit similar to Scala or Haskell type definitions.

Agree

**Comment by fomkin** [comment]
> We should carefully think about number. Sometimes it's impossible to print floating point number as string without losing precision. May we lose precision or not when sending this message to the user? We could print number as hex or base64 string, but this would make parsing harder.

Well, finally I don't think this is a problem.

**Comment by Chicker** [comment]
I think the using of any kind of delimiters in the string formats is error prone.

Why can't we use the following representation?

```
{
  "tpe": "int8",
  "value": -100
}

{
  "tpe": "boolean",
  "value": true
}

{
  "tpe": "number",
  "value": 2.0
}

{
  "tpe": "utf8",
  "value": "Here quotes \"\" and colon : may be"
}

{
  "tpe": "null",
  "value": null
}

{ 
  "tpe": "[int32]",
  "value": [12, 9, 42]
}
```

Maybe it is not a compact format, but I think we have no constraints about the size of the json.

**Comment by fomkin** [comment]
@Chicker There are several problems.

1. How to present structs? Key of struct item is primitive (not only string allowed).
2. Currently @vovapolu working under new test infrastructure for VM. Preconditions and expectations will be defined in YAML. Cases should be human readable and easy-to-write.

**Comment by fomkin** [comment]
@vovapolu As a non-regular user I want to feel comfort when I write tests :)

**Comment by Chicker** [comment]
> Can you give any examples of possible errors with prefix model?

In this implementation of the prefix model there is no obvious errors.
