### ISSUE TITLE
Allow to get all events by program (make event name optional)

### ISSUE THREAD

**Issue by fomkin** [expload/pravda#466]

**Comment by vovapolu** [comment]
In conclusion, we are going to add special index for `transactionId` and for other filters like by name and etc. we will just leave origin offset numbers from the order of **all** events for the program. It means for `transactionsId` you should always get at least one event (of cource, if `transactionId` is valid) and for other filters you can receive zero events for the given `offset` and `count`, in this situation you are supposed to increment `offset` and try again. You also receive origin offset numbers, it means you can receive inconsistent offsets, for example you can receive `1, 17, 142, 100000` offets for 4 filtered events.
