### ISSUE TITLE
.exe file parsing

### ISSUE THREAD

**Issue by vovapolu** [expload/pravda#51]
We still need to parse several things in the .exe file: 
- [x] local variables infromation
- [x] args infromation (signatures)
- [x] fields information (signatures, names)
- [x] c# attributes

**Comment by fomkin** [comment]
@vovapolu Does it still actual?

**Comment by vovapolu** [comment]
Yes, attributes aren't parsed yet.

**Comment by fomkin** [comment]
What about classes and interfaces?

**Comment by vovapolu** [comment]
What do you mean? There's `TypeDef` structure now, it contains signatures of all methods and fields.

**Comment by fomkin** [comment]
Ok.
