### ISSUE TITLE
Move Abci.EnvironmentProvider to node-storage

### ISSUE THREAD

**Issue by fomkin** [expload/pravda#63]
I'am encountered with problem with storage when solving #50. Currently `vmcli` module use it's own implementation of `vm.Storage`. It's just simple memory dumper. I thought why we can't use same implementation as node? It gives benefits.

1. ` Abci.EnvironmentProvider` writes effects log. It's useful for developer to see effects on application state.
2. Developer can make snapshots of mainnet (or current testnet) application state to run his program using production data. Dev matches prod!

Additional pros, cons?

**Comment by vovapolu** [comment]
@fomkin still actual?
