### ISSUE TITLE
CIL features translation

### ISSUE THREAD

**Issue by vovapolu** [expload/pravda#97]
We should translate the following CIL features:
- [x] `String`s (translation to `Word`s, concatination, other methods?) 
- [x] Byte arrays (`new byte[] {...}`, standard methods to work with them, mutability?)
- [x] Classes as structures (tables of virtual methods)
- [ ] const static fields
- [ ] Collections?

We should also block all other unimplemented stuff.

**Comment by pankratov** [comment]
It seems like virtual methods (if they are needed) should be supported in virtual machine.

**Comment by fomkin** [comment]
@pankratov why? virtual methods is just a table.

**Comment by vovapolu** [comment]
Outdated
